### ISSUE TITLE
Adding toString methods with radix argument

### ISSUE THREAD

**Issue by elyisgreat** [kiprobinson/BigFraction#5]
Just a quick little feature I thought I'd suggest. Much like BigInteger has a toString(radix) option, you could add a radix argument to your toString methods. That way fractions could be expressed in arbitrary bases. 57/11, for example, could be expressed in binary as 111001/1011, for example.

Implementing this for the default toString() methods should be trivial. toMixedString() shouldn't be that difficult either. toDecimalString() might be a little harder, but I'm sure it can be done.

**Comment by kiprobinson** [comment]
Done!

**Comment by elyisgreat** [comment]
Nice! 

I noticed toDecimalString() hasn't been implemented yet, though I imagine it's harder to do.

**Comment by elyisgreat** [comment]
Actually, I figured out how to implement it. 

```
  public String toDecimalString(int numDecimalDigits, int radix, RoundingMode roundingMode)
  {
    if(numDecimalDigits < 0)
      throw new IllegalArgumentException("numDecimalDigits must be nonnegative");
    
    //shortcut - if we don't want any decimal digits, this is equivalent to round()
    if(numDecimalDigits == 0)
      return this.round(roundingMode).toString();
    
    //multiply by 10^(digits), then round to integer
    BigInteger rounded = this.multiply(BigInteger.valueOf(radix).pow(numDecimalDigits)).round(roundingMode);
    
    //get the actual digits (ignoring the sign bit)
    String digits = rounded.abs().toString(radix);
    
    String beforeDecimal = "0";
    String afterDecimal = digits;
    int padLen = 0; //number of zeros we need to pad afterDecimal with with
    
    if(digits.length() > numDecimalDigits)
    {
      //we got too many digits... need to split into before/after decimal parts
      beforeDecimal = digits.substring(0, digits.length() - numDecimalDigits);
      afterDecimal = digits.substring(digits.length() - numDecimalDigits);
    }
    else if (digits.length() < numDecimalDigits)
    {
      //we don't have enough digits. We will have to pad with zeros
      padLen = numDecimalDigits - digits.length();
    }
    //else: we got exactly the right number of digits. nothing to do!
    
    //create string builder to hold result. init buffer to max possible size: lenth of parts plus length of padding plus space for . and -
    StringBuilder sb = new StringBuilder(beforeDecimal.length() + afterDecimal.length() + padLen + 2);
    
    if(rounded.signum() < 0)
      sb.append('-');
    
    sb.append(beforeDecimal).append('.');
    
    for(int i = 0; i < padLen; i++)
      sb.append('0');
    
    sb.append(afterDecimal);
    
    return sb.toString();
  }
```

**Comment by kiprobinson** [comment]
I will look at toDecimalString() later.

The existing name of the function is unfortunate, since "decimal" means base 10, and choosing a different radix would no longer make it a *decimal* representation. I will probably keep the function name the same for backwards compatibility, and also because as far as I can tell there is no good generalized name for non-fractional representation of a number in an arbitrary base. Here's someone asking http://math.stackexchange.com/questions/93315/name-for-decimals-in-other-bases

**Comment by elyisgreat** [comment]
imo "toRadixedString()" is a perfectly fine method name, and my modifications shouldn't make a difference to performance. 

Don't forget, though, that the different radices also have to be supported by the String constructor and valueOf method. Since these currently make use of BigDecimal, they'll probably have to be rewritten.

**Comment by kiprobinson** [comment]
I've added `toRadixedString(radix, numFractionalDigits)`, `toRadixedString(radix, numFractionalDigits, roundingMode)`, `valueOf(String, radix)`, and `BigFraction(String, radix)`. I left `toDecimalString()` as-is: it just calls `toRadixedString()` with radix defaulted to 10.

Let me know if you run into any issues using them and thanks again for the suggestions.

**Comment by elyisgreat** [comment]
Looks great!
